NextGeoss/ckanext-nextgeossharvest

- ckanext/nextgeossharvest/harvesters/gome2.py
> End date bug corrected

- ckanext/nextgeossharvest/lib/esa_base.py
Fixes #
Bug related with missing microseconds in DHuS results fixed.
> Bug related with missing microseconds in DHuS results fixed.

- ckanext/nextgeossharvest/lib/esa_base.py
Fixes #
All unknown collections were added. Now the harvester works properly for all the Sentinel-3 collections.
Collections added (collection_id):
SENTINEL3_OLCI_L1_EFR
SENTINEL3_OLCI_L1_ERR
SENTINEL3_OLCI_L2_LFR
SENTINEL3_OLCI_L2_LRR
SENTINEL3_SLSTR_L1_RBT
SENTINEL3_SLSTR_L2_LST
> Sentinel bug fixes

- .travis.yml
- ckanext/nextgeossharvest/harvesters/esa.py
limit datasets_per_page to 100, to avoid getting an error from the provider
> Set the limit for datasets_per_page to 100

- ckanext/nextgeossharvest/harvesters/probav.py
Fixes Saving identifier as a Title for the Dataset
> Remove parsing title, keep collection name as title

- ckanext/nextgeossharvest/harvesters/probav.py
Fixes #
Keep collection name as title
Change Start & Stop Time to timerange_start and timerange_end
> Probav title

- README.md
- ckanext/nextgeossharvest/harvesters/__init__.py
- ckanext/nextgeossharvest/harvesters/deimosimg.py
- ckanext/nextgeossharvest/lib/deimosimg_base.py
- ckanext/nextgeossharvest/lib/nextgeoss_base.py
- setup.py
Fixes #
New harvester for DEIMOS2 products (Data Source: Deimos Imaging via ftp). This harvester allows to collect 3 new collections:
- DE2_PM4_L1B (18 products)
- DE2_PSH_L1B (18 products)
- DE2_PSH_L1C (18 products)
The products are static, and **thus the harvester only needs to be run once**. The configuration to be used is detailed bellow:
{
"harvester_type":"deimos_imaging",
"username":"your_username",
"password":"your_password",
"make_private":false
}
> New DEIMOS2 ftp Harvester

- ckanext/nextgeossharvest/lib/esa_base.py
Fixes #
All unknown Sentinel-5P collections were added. Now the harvester works properly for all the Sentinel-5P collections.
Collections added (collection_id):
SENTINEL5P_OFFL_L1B
SENTINEL5P_OFFL_L2
SENTINEL5P_NRTI_L2
SENTINEL5P_RPRO_L2
> Sentinel 5p addition

- ckanext/nextgeossharvest/harvesters/probav.py
Fixes #
Bug fix (issue #97 ): Proba-V timeout no longer ignored
> Fix issue #97 - Proba-V timeout no longer ignored

- ckanext/nextgeossharvest/harvesters/cmems.py
- ckanext/nextgeossharvest/harvesters/esa.py
- ckanext/nextgeossharvest/harvesters/gome2.py
Reverts NextGeoss/ckanext-nextgeossharvest#70
> Revert "Restart from last good import after SQLAlchemy causes a bad import_stage"

- README.md
- ckanext/nextgeossharvest/harvesters/foodsecurity.py
- ckanext/nextgeossharvest/lib/nextgeoss_base.py
Fixes #
Add group and is_output to the harvester
nextgeoss_base updated to support groups in package_dict
Update README.md
> Food security with group

- ckanext/nextgeossharvest/harvesters/gome2.py
- ckanext/nextgeossharvest/lib/gome2_base.py
Fixes #
Regarding issue #115, the solution implemented is to make this time interval configurable through the harvest configuration. An example of a harvester configuration is:
```
{
"start_date": "2019-07-01",
"time_interval": 20,
"make_private": false
}
```
- Harvester log
> Issue #115 gome harvester stuck

- ckanext/nextgeossharvest/harvesters/probav.py
Regarding issue #132 :
* Remove harvest of metadata fields
* Restructure of resource parsing function
> ProbaV metadata update

- ckanext/nextgeossharvest/lib/modis_base.py
Regarding issue #135 and #137 
* Remove harvest of metadata fields
* Restructure of resource parsing function
> Modis harvester metadata update

- ckanext/nextgeossharvest/harvesters/foodsecurity.py
Regarding issue #139 
* Remove harvest of metadata fields
* Restructure of resource parsing function
> Food Security metadata update

- ckanext/nextgeossharvest/harvesters/deimosimg.py
- ckanext/nextgeossharvest/lib/deimosimg_base.py
Regarding issue #145 :
* Fix the incorrect metadata collection
Regarding issue #143 :
* Remove harvest metadata fields
* Restructure of resource parsing
> Deimos-2 metadata update:

- ckanext/nextgeossharvest/lib/cswsearch_base.py
- ckanext/nextgeossharvest/lib/plan4all_base.py
* Fix status flag in update_all functionality in cswsearch_base.py 
Regarding issue #149 #150 and #151 
* Reformulate metadata fields
* Restructure of resource parsing
> Plan4All harvester update

- ckanext/nextgeossharvest/harvesters/cmems.py
- ckanext/nextgeossharvest/lib/cmems_base.py
Regarding issue #153 :
* Restructure metadata field
* Restructure of the resource parsing function
> CMEMS harvester update

- ckanext/nextgeossharvest/harvesters/gdacs.py
- ckanext/nextgeossharvest/lib/gdacs_base.py
Fixes https://github.com/NextGeoss/ckanext-nextgeossharvest/issues/141
* Remove harvest of metadata fields
* Restructure of resource parsing
> GDACS metadata update

- ckanext/nextgeossharvest/lib/ebvs_base.py
* Remove information of collections not harvested
Regarding issue #156 
* Remove unwarranted metadata fields
* Restructure of the resource parsing function
- [] includes bugfix
> EBVs harvester update:

- ckanext/nextgeossharvest/harvesters/foodsecurity.py
Fixes #
Regarding issue #123, the harvester now looks forward in time fixing the issue described, if
- the number of products gathered is zero (already implemented in previous iterations)
- the harvester `update_all` is set to true (proposed fix)
> Fix - Foodsecurity harvester stuck updating the same dataset

- ckanext/nextgeossharvest/harvesters/gdacs.py
- ckanext/nextgeossharvest/lib/gdacs_base.py
Regarding issue #182 
* Add update_all to harvester configuration to allow the update of datasets from
> Add feature to update GDACS datasets

- ckanext/nextgeossharvest/lib/ebas_base.py
Regarding issue #168 
* Restructure of resource parsing function
Regarding issue #177 
* Remove order from resource metadata
Regarding issue #183 
* Remove Remove harvest of metadata fields
> EBAS harvester update

- ckanext/nextgeossharvest/harvesters/modis.py
Regarding issue #181 
* Add update_all to harvester configuration to allow the update of datasets from MODIS
> Add feature to update all MODIS datasets

- ckanext/nextgeossharvest/harvesters/probav.py
Regarding issue #180 
* Add update_all to harvester configuration to allow the update of datasets from Proba-V
> Add feature to update all Proba-V datasets

- ckanext/nextgeossharvest/harvesters/ebas.py
Regarding issue #161 :
* Add update_all to harvester configuration to allow the update of datasets from EBAS-NILU
> Add feature to update all EBAS-NILU datasets

- ckanext/nextgeossharvest/harvesters/cgss1.py
Regarding issue #157 
* Remove unwarranted metadata fields
Regarding issue #168 
* Restructure of the resource parsing function
> CGSS1 harvester update

- ckanext/nextgeossharvest/harvesters/simocean.py
- ckanext/nextgeossharvest/lib/simocean_base.py
Regarding issue #171 
* Remove metadata fields 
* Add update_all functionality (to behave properly requires PR #198 )
Regarding issue #168 
* Restructure resource parsing function
- [] includes user-visible changes
> SIMOcean harvester update

- ckanext/nextgeossharvest/collection_description/satcen_better.py
- ckanext/nextgeossharvest/harvesters/cmems.py
- ckanext/nextgeossharvest/harvesters/satcen_better.py
- ckanext/nextgeossharvest/interfaces/opensearch.py
- ckanext/nextgeossharvest/lib/deimosimg_base.py
- Change filename pattern for CMEMS products for the collection Global Total Surface and 15m Current - Hourly (mog)
- Change resource's URL protocol for Deimos-2 products
- Fix collection name and description of a SATCEN-BETTER collection
> Bugfix: Harvesters CMEMS, Deimos2 and Satcen

- ckanext/nextgeossharvest/harvesters/__init__.py
- ckanext/nextgeossharvest/harvesters/noa_epidemics.py
- ckanext/nextgeossharvest/lib/noa_epidemics_base.py
- requirements.txt
- setup.py
---
- Collection name: EYWA (NOA-BEYOND) Aedes Products
- Collection id: eywa_aedes_products
- Collection description: A 10-years’ time-series of environmental, meteorological and geomorphological data for every mosquito-trap in five countries, regarding Aedes mosquitoes. Satellite indices created and opened by EYWA. For more information please visit: http://beyond-eocenter.eu/index.php/web-services/eywa
- Number of Datasets: ~4500
- Collection name: EYWA (NOA-BEYOND) Culex Products
- Collection id: eywa_culex_products
- Collection description: A 10-years’ time-series of environmental, meteorological and geomorphological data for every mosquito-trap in five countries, regarding Culex mosquitoes. Satellite indices created and opened by EYWA. For more information please visit: …
> Noa Epidemics Harvester

- ckanext/nextgeossharvest/lib/fsscat_base.py
Fixes #
- [ x] includes bugfix
> Removed Note:... from resource description

- ckanext/nextgeossharvest/harvesters/noa_epidemics.py
- ckanext/nextgeossharvest/lib/noa_epidemics_base.py
Updates in order to harvest from new API. 
---
Collection name: EYWA (NOA-BEYOND) Aedes Products
Collection id: eywa_aedes_products
Collection description: A 10-years’ time-series of environmental, meteorological and geomorphological data for every mosquito-trap in five countries, regarding Aedes mosquitoes. Satellite indices created and opened by EYWA. For more information please visit: http://beyond-eocenter.eu/index.php/web-services/eywa
Number of Datasets: 10082
Collection name: EYWA (NOA-BEYOND) Culex Products
Collection id: eywa_culex_products
Collection description: A 10-years’ time-series of environmental, meteorological and geomorphological data for every mosquito-trap in five countries, regarding Culex mosquitoes. Satellite indices created and opened by EYWA. For more …
> Updates for API changes

- ckanext/nextgeossharvest/lib/noa_epidemics_base.py
Fixes #
A change in the download URL was made.
Previous URL was returning error 404.
> Download URL change
